import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import 'bootstrap/dist/css/bootstrap.min.css';
import {Container, Row, Col} from 'react-bootstrap'

// components

import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";



const montserrat = Montserrat({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
      <body>
          <Container fluid style={{padding: 0}}>
            <Header />
            {children}
            <Footer />
          </Container>
          </body>
    </html>
  );
}
